# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2471e416cbbc6280b0547d41a55b7ac5908e89905969a32633f8b01e8ce3627af6e1b3442015c93ea83c3b727ecf45a75d3b8d183c2b2b2798df714106e93313

test:
  secret_key_base: fbf0139552ac178a026b2ae280ac26e2616837ab817bae492f79f36550f61d21597ad2f5e90db93157ca166faeca64c7df6f504f6b60d3476ee72915956c9dfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
